# Generated by Django 5.2.8 on 2025-12-01 02:01

import auto_prefetch
import core.helper.models
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timetable', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.CharField(default=core.helper.models.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the session e.g. 2024/2025', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('school', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_sessions', to='users.school')),
            ],
            options={
                'verbose_name': 'Academic Session',
                'verbose_name_plural': 'Academic Sessions',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
                'unique_together': {('school', 'name')},
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.CharField(default=core.helper.models.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='1st Term, 2nd Term, 3rd Term', max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('session', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='accessments.academicsession')),
            ],
            options={
                'verbose_name': 'Academic Term',
                'verbose_name_plural': 'Academic Terms',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
                'unique_together': {('session', 'name')},
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentPolicy',
            fields=[
                ('id', models.CharField(default=core.helper.models.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Default Policy', max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('school', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_policies', to='users.school')),
                ('term', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='accessments.academicterm')),
            ],
            options={
                'verbose_name': 'Assessment Policy',
                'verbose_name_plural': 'Assessment Policies',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentType',
            fields=[
                ('id', models.CharField(default=core.helper.models.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('count', models.PositiveIntegerField(default=1)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_score', models.PositiveIntegerField(default=100)),
                ('is_optional', models.BooleanField(default=False)),
                ('policy', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_types', to='accessments.assessmentpolicy')),
            ],
            options={
                'verbose_name': 'Assessment Type',
                'verbose_name_plural': 'Assessment Types',
                'ordering': ['policy', 'name'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentRecord',
            fields=[
                ('id', models.CharField(default=core.helper.models.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('index', models.PositiveIntegerField(help_text='Test/Exam number e.g. 1 or 2')),
                ('score', models.FloatField(blank=True, null=True)),
                ('classroom_subject', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_records', to='timetable.subject')),
                ('student', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_records', to='users.studentprofile')),
                ('assessment_type', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='accessments.assessmenttype')),
            ],
            options={
                'verbose_name': 'Assessment Record',
                'verbose_name_plural': 'Assessment Records',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GradeScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=2)),
                ('min_score', models.PositiveIntegerField()),
                ('max_score', models.PositiveIntegerField()),
                ('point', models.DecimalField(decimal_places=1, max_digits=3)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('school', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.school')),
            ],
            options={
                'verbose_name': 'Grade Scale',
                'verbose_name_plural': 'Grade Scales',
                'ordering': ['-max_score'],
            },
        ),
        migrations.CreateModel(
            name='SubjectResult',
            fields=[
                ('id', models.CharField(default=core.helper.models.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_ca', models.FloatField(default=0)),
                ('exam_score', models.FloatField(default=0)),
                ('total_score', models.FloatField(default=0)),
                ('grade', models.CharField(blank=True, max_length=2, null=True)),
                ('grade_point', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('classroom_subject', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.subject')),
                ('student', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studentprofile')),
                ('term', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessments.academicterm')),
            ],
            options={
                'verbose_name': 'Subject Result',
                'verbose_name_plural': 'Subject Results',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TermReportSummary',
            fields=[
                ('id', models.CharField(default=core.helper.models.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_score', models.FloatField(default=0)),
                ('average_score', models.FloatField(default=0)),
                ('total_points', models.FloatField(default=0)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('class_position', models.PositiveIntegerField(blank=True, null=True)),
                ('student', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studentprofile')),
                ('term', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessments.academicterm')),
            ],
            options={
                'verbose_name': 'Term Report Summary',
                'verbose_name_plural': 'Term Report Summaries',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='assessmentpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('school', 'term', 'is_active'), name='unique_active_policy_per_school_term'),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentrecord',
            unique_together={('student', 'classroom_subject', 'assessment_type', 'index')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectresult',
            unique_together={('student', 'classroom_subject', 'term')},
        ),
        migrations.AlterUniqueTogether(
            name='termreportsummary',
            unique_together={('student', 'term')},
        ),
    ]
