# Generated by Django 5.2.8 on 2025-12-02 01:46

import auto_prefetch
import core.helper.models
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('accessments', '0001_initial'),
        ('timetable', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessmenttype',
            options={'base_manager_name': 'prefetch_manager', 'ordering': ['policy', 'order', 'name'], 'verbose_name': 'Assessment Type', 'verbose_name_plural': 'Assessment Types'},
        ),
        migrations.AddField(
            model_name='academicterm',
            name='term_type',
            field=models.CharField(choices=[('HALF_TERM', 'Half Term'), ('END_OF_TERM', 'End of Term'), ('FULL_TERM', 'Full Term')], default='END_OF_TERM', max_length=20),
        ),
        migrations.AddField(
            model_name='assessmentrecord',
            name='date_taken',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmenttype',
            name='category',
            field=models.CharField(choices=[('CA', 'Continuous Assessment'), ('EXAM', 'Examination'), ('HALF_TERM', 'Half Term Exam'), ('PROJECT', 'Project'), ('ASSIGNMENT', 'Assignment')], default='CA', max_length=20),
        ),
        migrations.AddField(
            model_name='assessmenttype',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order in reports'),
        ),
        migrations.AddField(
            model_name='gradescale',
            name='display_name',
            field=models.CharField(blank=True, help_text="e.g., A' for honors", max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='gradescale',
            name='is_honors',
            field=models.BooleanField(default=False, help_text="Whether this is an honors grade (A')"),
        ),
        migrations.AddField(
            model_name='subjectresult',
            name='average_score',
            field=models.FloatField(default=0, help_text='Average score for the subject'),
        ),
        migrations.AddField(
            model_name='subjectresult',
            name='half_term_score',
            field=models.FloatField(default=0, help_text='Score for half-term exams'),
        ),
        migrations.AddField(
            model_name='termreportsummary',
            name='attendance_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='termreportsummary',
            name='class_group',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.classroom'),
        ),
        migrations.AddField(
            model_name='termreportsummary',
            name='conduct_rating',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='termreportsummary',
            name='form_teacher_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='termreportsummary',
            name='principal_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='termreportsummary',
            name='target_gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='gradescale',
            name='grade',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='subjectresult',
            name='grade',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='gradescale',
            unique_together={('school', 'grade', 'is_honors')},
        ),
        migrations.CreateModel(
            name='TeacherComment',
            fields=[
                ('id', models.CharField(default=core.helper.models.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField()),
                ('comment_type', models.CharField(choices=[('STRENGTH', 'Strength'), ('WEAKNESS', 'Weakness'), ('GENERAL', 'General'), ('IMPROVEMENT', 'Area for Improvement')], default='GENERAL', max_length=20)),
                ('subject_result', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_comments', to='accessments.subjectresult')),
                ('teacher', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacherprofile')),
            ],
            options={
                'verbose_name': 'Teacher Comment',
                'verbose_name_plural': 'Teacher Comments',
                'ordering': ['subject_result', 'comment_type'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TargetGrade',
            fields=[
                ('id', models.CharField(default=core.helper.models.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_grade', models.CharField(max_length=3)),
                ('target_point', models.DecimalField(decimal_places=1, max_digits=3)),
                ('current_grade', models.CharField(blank=True, max_length=3, null=True)),
                ('current_point', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('classroom_subject', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.subject')),
                ('student', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studentprofile')),
                ('term', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessments.academicterm')),
            ],
            options={
                'verbose_name': 'Target Grade',
                'verbose_name_plural': 'Target Grades',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
                'unique_together': {('student', 'classroom_subject', 'term')},
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
