# Generated by Django 5.2.8 on 2025-12-02 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessments', '0002_alter_assessmenttype_options_academicterm_term_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicterm',
            name='term_type',
            field=models.CharField(choices=[('HALF_TERM', 'Half Term'), ('END_OF_TERM', 'End of Term'), ('FULL_TERM', 'Full Term')], default='FULL_TERM', max_length=20),
        ),
    ]
