# Generated by Django 5.2.8 on 2025-12-02 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessments', '0003_alter_academicterm_term_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradescale',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gradescale',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
