# Generated by Django 5.2.8 on 2025-12-02 04:43

import core.helper.models
import django.db.models.manager
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessments', '0004_gradescale_is_active_gradescale_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradescale',
            options={'base_manager_name': 'prefetch_manager', 'ordering': ['-max_score'], 'verbose_name': 'Grade Scale', 'verbose_name_plural': 'Grade Scales'},
        ),
        migrations.AlterModelManagers(
            name='gradescale',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='gradescale',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gradescale',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='gradescale',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='gradescale',
            name='id',
            field=models.CharField(default=core.helper.models.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False, unique=True),
        ),
    ]
