# Generated by Django 5.2.8 on 2025-12-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessments', '0005_alter_gradescale_options_alter_gradescale_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentpolicy',
            name='ca_weight',
            field=models.PositiveIntegerField(default=40, help_text='Continuous Assessment weight (%)'),
        ),
        migrations.AddField(
            model_name='assessmentpolicy',
            name='exam_weight',
            field=models.PositiveIntegerField(default=60, help_text='Examination weight (%)'),
        ),
    ]
