# Generated by Django 5.2.8 on 2025-11-14 09:15

import auto_prefetch
import core.helper.models
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.CharField(default=core.helper.models.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the subject (e.g., Mathematics, Physics)', max_length=100, verbose_name='Subject Name')),
                ('code', models.CharField(help_text='Unique code for the subject (e.g., MATH101)', max_length=20, unique=True, verbose_name='Subject Code')),
                ('description', models.TextField(blank=True, help_text='Brief description of the subject', null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this subject is currently being taught', verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'db_table': 'subjects',
                'ordering': ['name'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.CharField(default=core.helper.models.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="E.g., 'Period 1', 'Break', 'Lunch'", max_length=50, verbose_name='Period Name')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('is_break', models.BooleanField(default=False, help_text='Check if this is a break/lunch period', verbose_name='Is Break Period')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which periods appear in the day', verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Time Slot',
                'verbose_name_plural': 'Time Slots',
                'db_table': 'time_slots',
                'ordering': ['order', 'start_time'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.CharField(default=core.helper.models.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_class', models.CharField(choices=[('Nursery 1', 'Nursery 1'), ('Nursery 2', 'Nursery 2'), ('Prep', 'Preparatory'), ('Primary 1', 'Primary 1'), ('Primary 2', 'Primary 2'), ('Primary 3', 'Primary 3'), ('Primary 4', 'Primary 4'), ('Primary 5', 'Primary 5'), ('Primary 6', 'Primary 6'), ('JSS1', 'Junior Secondary 1'), ('JSS2', 'Junior Secondary 2'), ('JSS3', 'Junior Secondary 3'), ('SS1', 'Senior Secondary 1'), ('SS2', 'Senior Secondary 2'), ('SS3', 'Senior Secondary 3')], help_text='Which class this schedule is for', max_length=50, verbose_name='Class')),
                ('day_of_week', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=20, verbose_name='Day of Week')),
                ('room_number', models.CharField(blank=True, help_text='Classroom or lab number', max_length=50, null=True, verbose_name='Room Number')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this schedule is currently in effect', verbose_name='Is Active')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or instructions', null=True, verbose_name='Notes')),
                ('teacher', auto_prefetch.ForeignKey(blank=True, help_text='Teacher assigned to this class', limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Teacher')),
                ('subject', auto_prefetch.ForeignKey(blank=True, help_text='Leave blank for break periods', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='timetable.subject', verbose_name='Subject')),
                ('time_slot', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='timetable.timeslot', verbose_name='Time Slot')),
            ],
            options={
                'verbose_name': 'Class Schedule',
                'verbose_name_plural': 'Class Schedules',
                'db_table': 'class_schedules',
                'ordering': ['academic_class', 'day_of_week', 'time_slot__order'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
                'unique_together': {('academic_class', 'day_of_week', 'time_slot')},
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.CharField(default=core.helper.models.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="E.g., 'Fall 2024 Timetable'", max_length=100, verbose_name='Timetable Name')),
                ('academic_year', models.CharField(help_text="E.g., '2024-2025'", max_length=20, verbose_name='Academic Year')),
                ('term', models.CharField(help_text="E.g., 'Fall Semester', 'First Term'", max_length=50, verbose_name='Term/Semester')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('is_active', models.BooleanField(default=True, help_text='Only one timetable should be active at a time', verbose_name='Is Active')),
                ('schedules', models.ManyToManyField(help_text='All schedules included in this timetable', related_name='timetables', to='timetable.classschedule', verbose_name='Class Schedules')),
            ],
            options={
                'verbose_name': 'Timetable',
                'verbose_name_plural': 'Timetables',
                'db_table': 'timetables',
                'ordering': ['-start_date'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
