# Generated by Django 5.2.8 on 2025-12-02 02:04

import auto_prefetch
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('timetable', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'base_manager_name': 'prefetch_manager', 'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='subject',
            name='class_rooms',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='academics.classroom'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='school',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='users.school'),
        ),
        migrations.AlterModelTable(
            name='subject',
            table=None,
        ),
    ]
