# Generated by Django 5.2.8 on 2025-12-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='subjects',
            field=models.ManyToManyField(blank=True, help_text='Subjects this teacher can teach.', related_name='teachers', to='academics.subject'),
        ),
    ]
