# Generated by Django 5.2.8 on 2026-04-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_adminprofile_status_alter_parentprofile_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('action_required', 'Action Required'), ('requires_update', 'Requires Update')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('action_required', 'Action Required'), ('requires_update', 'Requires Update')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('action_required', 'Action Required'), ('requires_update', 'Requires Update')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('action_required', 'Action Required'), ('requires_update', 'Requires Update')], default='pending', max_length=20),
        ),
    ]
