# Generated by Django 5.2.8 on 2025-12-13 18:13

import auto_prefetch
import core.helper.models
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('users', '0002_teacherprofile_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='admission_date',
            field=models.DateField(blank=True, help_text='Date student was officially admitted.', null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='current_class',
            field=models.CharField(blank=True, choices=[('Nursery 1', 'Nursery 1'), ('Nursery 2', 'Nursery 2'), ('Prep', 'Preparatory'), ('Primary 1', 'Primary 1'), ('Primary 2', 'Primary 2'), ('Primary 3', 'Primary 3'), ('Primary 4', 'Primary 4'), ('Primary 5', 'Primary 5'), ('Primary 6', 'Primary 6'), ('JSS1', 'Junior Secondary 1'), ('JSS2', 'Junior Secondary 2'), ('JSS3', 'Junior Secondary 3'), ('SS1', 'Senior Secondary 1'), ('SS2', 'Senior Secondary 2'), ('SS3', 'Senior Secondary 3')], help_text="Student's current academic level (e.g. JSS1, SS2).", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_id',
            field=models.CharField(blank=True, editable=False, help_text='Automatically generated unique student identifier.', max_length=50, unique=True, verbose_name='Student ID'),
        ),
        migrations.CreateModel(
            name='StudentContact',
            fields=[
                ('id', models.CharField(default=core.helper.models.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Full name of the contact person.', max_length=255)),
                ('relationship', models.CharField(help_text='Relationship to student e.g. Father, Mother, Guardian.', max_length=100)),
                ('phone', models.CharField(help_text='Primary phone number.', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Optional email address.', max_length=254, null=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Marks this contact as the primary guardian.')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='users.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.CharField(default=core.helper.models.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text="Indicates the student's current active enrollment.")),
                ('classroom', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.classroom')),
                ('session', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='users.studentprofile')),
                ('term', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.academicterm')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
                'constraints': [models.UniqueConstraint(fields=('student', 'session', 'term'), name='unique_student_enrollment_per_term')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
