# Generated by Django 5.2.8 on 2026-03-13 09:45

import core.helper.media
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_school_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=core.helper.media.MediaHelper.get_image_upload_path),
        ),
    ]
