# Generated by Django 5.2.8 on 2026-04-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_adminprofile_status_alter_parentprofile_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='custom_domain',
            field=models.CharField(blank=True, help_text='Optional fully-qualified custom domain for this school. e.g. portal.greenfield.edu.ng', max_length=253, null=True, unique=True, verbose_name='Custom Domain'),
        ),
        migrations.AddField(
            model_name='school',
            name='db_alias',
            field=models.CharField(db_index=True, default='default', editable=False, help_text="The Django DATABASES key for this tenant. 'default' for shared-plan schools. Auto-set to 'school_<slug>' when promoted to isolated tier.", max_length=100, verbose_name='Database Alias'),
        ),
        migrations.AddField(
            model_name='school',
            name='db_tier',
            field=models.CharField(choices=[('shared', 'Shared Database'), ('isolated', 'Isolated Database')], default='shared', help_text='SHARED: school data lives in the shared default database. ISOLATED: school data lives in its own dedicated database.', max_length=20, verbose_name='Database Tier'),
        ),
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.CharField(blank=True, help_text='Physical address of the school', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates if the school is currently active'),
        ),
        migrations.AlterField(
            model_name='school',
            name='max_students',
            field=models.PositiveIntegerField(default=1000, help_text='Maximum number of students the school can accommodate'),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(help_text='Official name of the school', max_length=255),
        ),
        migrations.AlterField(
            model_name='school',
            name='slug',
            field=models.SlugField(help_text='URL-friendly identifier auto-generated from the school name', unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='subscription_expiry',
            field=models.DateField(blank=True, help_text="Date when the school's subscription expires", null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='subscription_plan',
            field=models.CharField(blank=True, help_text='Name of the subscription plan the school is on', max_length=50, null=True),
        ),
    ]
