# Generated by Django 5.2.8 on 2026-04-20 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_school_custom_domain_school_db_alias_school_db_tier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcontact',
            name='school',
            field=models.ForeignKey(help_text='The school (tenant) this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='users.school'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='school',
            field=models.ForeignKey(help_text='The school (tenant) this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='users.school'),
        ),
    ]
