# Generated by Django 5.2.8 on 2025-11-24 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_parentprofile_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='owner',
        ),
    ]
