# Generated by Django 5.2.8 on 2025-11-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_school_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='admin_type',
            field=models.CharField(choices=[('school_owner', 'School Owner'), ('principal', 'Principal'), ('vice_principal', 'Vice Principal'), ('bursar', 'Bursar'), ('hr', 'Human Resources Admin'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
