# Generated by Django 5.2.8 on 2025-11-26 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_adminprofile_admin_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='approved_by',
            field=models.CharField(blank=True, help_text='Email of the admin who approved or rejected this profile.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Approval status for this profile.', max_length=20),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='approved_by',
            field=models.CharField(blank=True, help_text='Email of the admin who approved or rejected this profile.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Approval status for this profile.', max_length=20),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='approved_by',
            field=models.CharField(blank=True, help_text='Email of the admin who approved or rejected this profile.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Approval status for this profile.', max_length=20),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='admin_type',
            field=models.CharField(choices=[('school_owner', 'School Owner'), ('principal', 'Principal'), ('vice_principal', 'Vice Principal'), ('bursar', 'Bursar'), ('hr', 'Human Resources Admin'), ('other', 'Other')], default='other', help_text='Type of administrative role this user holds.', max_length=50),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='user',
            field=models.OneToOneField(help_text='The user linked to this profile.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='user',
            field=models.OneToOneField(help_text='The user linked to this profile.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='approved_by',
            field=models.CharField(blank=True, help_text='Email of the admin who approved or rejected this profile.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Approval status for this profile.', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_id',
            field=models.CharField(blank=True, editable=False, help_text='Automatically generated student identifier.', max_length=50, unique=True, verbose_name='Student ID'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(help_text='The user linked to this profile.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='user',
            field=models.OneToOneField(help_text='The user linked to this profile.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
