# Generated by Django 5.2.8 on 2025-11-26 19:09

import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('users', '0008_studentprofile_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='classroom',
            field=auto_prefetch.ForeignKey(blank=True, help_text='Classroom assigned to this teacher.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='academics.classroom'),
        ),
    ]
