# Generated by Django 5.2.8 on 2026-04-04 08:17

import auto_prefetch
import core.helper.models
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectResult',
            fields=[
                ('id', models.CharField(default=core.helper.models.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_ca', models.FloatField(default=0)),
                ('exam_score', models.FloatField(default=0)),
                ('half_term_score', models.FloatField(default=0, help_text='Score for half-term exams')),
                ('total_score', models.FloatField(default=0)),
                ('average_score', models.FloatField(default=0, help_text='Average score for the subject')),
                ('grade', models.CharField(blank=True, max_length=3, null=True)),
                ('grade_point', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Subject Result',
                'verbose_name_plural': 'Subject Results',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TargetGrade',
            fields=[
                ('id', models.CharField(default=core.helper.models.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_grade', models.CharField(max_length=3)),
                ('target_point', models.DecimalField(decimal_places=1, max_digits=3)),
                ('current_grade', models.CharField(blank=True, max_length=3, null=True)),
                ('current_point', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
            ],
            options={
                'verbose_name': 'Target Grade',
                'verbose_name_plural': 'Target Grades',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TeacherComment',
            fields=[
                ('id', models.CharField(default=core.helper.models.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField()),
                ('comment_type', models.CharField(choices=[('STRENGTH', 'Strength'), ('WEAKNESS', 'Weakness'), ('GENERAL', 'General'), ('IMPROVEMENT', 'Area for Improvement')], default='GENERAL', max_length=20)),
            ],
            options={
                'verbose_name': 'Teacher Comment',
                'verbose_name_plural': 'Teacher Comments',
                'ordering': ['subject_result', 'comment_type'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TermReportSummary',
            fields=[
                ('id', models.CharField(default=core.helper.models.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_score', models.FloatField(default=0)),
                ('average_score', models.FloatField(default=0)),
                ('total_points', models.FloatField(default=0)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('target_gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('class_position', models.PositiveIntegerField(blank=True, null=True)),
                ('attendance_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('conduct_rating', models.CharField(blank=True, max_length=20, null=True)),
                ('principal_comment', models.TextField(blank=True, null=True)),
                ('form_teacher_comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Term Report Summary',
                'verbose_name_plural': 'Term Report Summaries',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GradeScale',
            fields=[
                ('id', models.CharField(default=core.helper.models.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('grade', models.CharField(max_length=3)),
                ('display_name', models.CharField(blank=True, help_text="e.g., A' for honors", max_length=50, null=True)),
                ('min_score', models.PositiveIntegerField()),
                ('max_score', models.PositiveIntegerField()),
                ('point', models.DecimalField(decimal_places=1, max_digits=3)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('is_honors', models.BooleanField(default=False, help_text="Whether this is an honors grade (A')")),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('class_room', auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_scales', to='academics.classroom')),
            ],
            options={
                'verbose_name': 'Grade Scale',
                'verbose_name_plural': 'Grade Scales',
                'ordering': ['-max_score'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
