# Generated by Django 5.2.8 on 2025-12-07 12:09

import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('grading', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradescale',
            name='school',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.school'),
        ),
        migrations.AddField(
            model_name='subjectresult',
            name='classroom_subject',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject'),
        ),
        migrations.AddField(
            model_name='subjectresult',
            name='student',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='subjectresult',
            name='term',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academicterm'),
        ),
        migrations.AddField(
            model_name='targetgrade',
            name='classroom_subject',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject'),
        ),
        migrations.AddField(
            model_name='targetgrade',
            name='student',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='targetgrade',
            name='term',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academicterm'),
        ),
        migrations.AddField(
            model_name='teachercomment',
            name='subject_result',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_comments', to='grading.subjectresult'),
        ),
        migrations.AddField(
            model_name='teachercomment',
            name='teacher',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacherprofile'),
        ),
        migrations.AddField(
            model_name='termreportsummary',
            name='class_group',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.classroom'),
        ),
        migrations.AddField(
            model_name='termreportsummary',
            name='student',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='termreportsummary',
            name='term',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academicterm'),
        ),
        migrations.AlterUniqueTogether(
            name='gradescale',
            unique_together={('school', 'grade', 'is_honors')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectresult',
            unique_together={('student', 'classroom_subject', 'term')},
        ),
        migrations.AlterUniqueTogether(
            name='targetgrade',
            unique_together={('student', 'classroom_subject', 'term')},
        ),
        migrations.AlterUniqueTogether(
            name='termreportsummary',
            unique_together={('student', 'term')},
        ),
    ]
