# Generated by Django 5.2.8 on 2026-04-21 11:55

import auto_prefetch
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('grading', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradescale',
            name='school',
            field=models.ForeignKey(help_text='The school (tenant) this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='users.school'),
        ),
        migrations.AddField(
            model_name='gradescale',
            name='term',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_scales', to='academics.academicterm'),
        ),
        migrations.AddField(
            model_name='subjectresult',
            name='classroom_subject',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_results', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='subjectresult',
            name='student',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_results', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='subjectresult',
            name='term',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_results', to='academics.academicterm'),
        ),
        migrations.AddField(
            model_name='targetgrade',
            name='classroom_subject',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject'),
        ),
        migrations.AddField(
            model_name='targetgrade',
            name='student',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_grades', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='targetgrade',
            name='term',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academicterm'),
        ),
        migrations.AddField(
            model_name='teachercomment',
            name='subject_result',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_comments', to='grading.subjectresult'),
        ),
        migrations.AddField(
            model_name='teachercomment',
            name='teacher',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacherprofile'),
        ),
        migrations.AddField(
            model_name='termreportsummary',
            name='class_group',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term_summaries', to='academics.classroom'),
        ),
        migrations.AddField(
            model_name='termreportsummary',
            name='student',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_summaries', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='termreportsummary',
            name='term',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_summaries', to='academics.academicterm'),
        ),
        migrations.AddConstraint(
            model_name='gradescale',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper(django.db.models.functions.text.Trim('grade')), models.F('school'), models.F('term'), models.F('class_room'), condition=models.Q(('is_active', True)), name='unique_active_grade_per_scope'),
        ),
        migrations.AddConstraint(
            model_name='gradescale',
            constraint=models.CheckConstraint(condition=models.Q(('min_score__lte', models.F('max_score'))), name='min_score_lte_max_score'),
        ),
        migrations.AddConstraint(
            model_name='gradescale',
            constraint=models.CheckConstraint(condition=models.Q(('min_score__gte', 0), ('max_score__lte', 100)), name='score_range_0_100'),
        ),
        migrations.AddConstraint(
            model_name='gradescale',
            constraint=models.CheckConstraint(condition=models.Q(('point__gte', 0), ('point__lte', 5)), name='point_between_0_and_5'),
        ),
        migrations.AlterUniqueTogether(
            name='subjectresult',
            unique_together={('student', 'classroom_subject', 'term', 'stage')},
        ),
        migrations.AlterUniqueTogether(
            name='targetgrade',
            unique_together={('student', 'classroom_subject', 'term')},
        ),
        migrations.AlterUniqueTogether(
            name='termreportsummary',
            unique_together={('student', 'term', 'stage', 'class_group')},
        ),
    ]
