# Generated by Django 5.2.8 on 2026-04-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectresult',
            name='stage',
            field=models.CharField(choices=[('HALF_TERM', 'Half Term'), ('END_OF_TERM', 'End of Term')], default='END_OF_TERM', help_text='Assessment stage this result belongs to', max_length=20),
        ),
    ]
