# Generated by Django 5.2.8 on 2025-12-09 12:11

import auto_prefetch
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('grading', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradescale',
            name='class_room',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_scales', to='academics.classroom'),
        ),
        migrations.AddField(
            model_name='gradescale',
            name='effective_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gradescale',
            name='effective_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gradescale',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gradescale',
            name='term',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_scales', to='academics.academicterm'),
        ),
        migrations.AddField(
            model_name='gradescale',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
