# Generated by Django 5.2.8 on 2025-12-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0003_gradescale_class_room_gradescale_effective_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradescale',
            name='display_name',
            field=models.CharField(blank=True, help_text="e.g., A' for honors", max_length=50, null=True),
        ),
    ]
