# Generated by Django 5.2.8 on 2026-04-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0003_subjectresult_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='termreportsummary',
            name='stage',
            field=models.CharField(choices=[('HALF_TERM', 'Half Term'), ('END_OF_TERM', 'End of Term')], default='END_OF_TERM', max_length=20),
        ),
    ]
