# Generated by Django 5.2.8 on 2025-12-13 18:13

import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0004_alter_gradescale_display_name'),
        ('users', '0002_teacherprofile_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetgrade',
            name='student',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_grades', to='users.studentprofile'),
        ),
    ]
