# Generated by Django 5.2.8 on 2026-04-10 11:23

import auto_prefetch
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_assessmentrecord_remarks_assessmentrecord_status'),
        ('grading', '0004_termreportsummary_stage'),
        ('users', '0003_alter_adminprofile_status_alter_parentprofile_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subjectresult',
            options={'base_manager_name': 'prefetch_manager', 'ordering': ['term', 'stage'], 'verbose_name': 'Subject Result', 'verbose_name_plural': 'Subject Results'},
        ),
        migrations.AlterModelOptions(
            name='termreportsummary',
            options={'base_manager_name': 'prefetch_manager', 'ordering': ['term', 'stage', 'class_position'], 'verbose_name': 'Term Report Summary', 'verbose_name_plural': 'Term Report Summaries'},
        ),
        migrations.AlterUniqueTogether(
            name='subjectresult',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='termreportsummary',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='subjectresult',
            name='average_score',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Average across assessment categories', max_digits=6),
        ),
        migrations.AlterField(
            model_name='subjectresult',
            name='classroom_subject',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_results', to='academics.subject'),
        ),
        migrations.AlterField(
            model_name='subjectresult',
            name='exam_score',
            field=models.DecimalField(decimal_places=2, default=0, help_text='End of term exam score', max_digits=6),
        ),
        migrations.AlterField(
            model_name='subjectresult',
            name='half_term_score',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Score at half term checkpoint', max_digits=6),
        ),
        migrations.AlterField(
            model_name='subjectresult',
            name='student',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_results', to='users.studentprofile'),
        ),
        migrations.AlterField(
            model_name='subjectresult',
            name='term',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_results', to='academics.academicterm'),
        ),
        migrations.AlterField(
            model_name='subjectresult',
            name='total_ca',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Aggregated continuous assessment score', max_digits=6),
        ),
        migrations.AlterField(
            model_name='subjectresult',
            name='total_score',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Final weighted total score out of 100', max_digits=6),
        ),
        migrations.AlterField(
            model_name='termreportsummary',
            name='average_score',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Average total_score across all subjects', max_digits=6),
        ),
        migrations.AlterField(
            model_name='termreportsummary',
            name='class_group',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term_summaries', to='academics.classroom'),
        ),
        migrations.AlterField(
            model_name='termreportsummary',
            name='gpa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Grade point average for the term', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='termreportsummary',
            name='stage',
            field=models.CharField(choices=[('HALF_TERM', 'Half Term'), ('END_OF_TERM', 'End of Term')], default='END_OF_TERM', help_text='Assessment stage this summary belongs to', max_length=20),
        ),
        migrations.AlterField(
            model_name='termreportsummary',
            name='student',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_summaries', to='users.studentprofile'),
        ),
        migrations.AlterField(
            model_name='termreportsummary',
            name='target_gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='termreportsummary',
            name='term',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_summaries', to='academics.academicterm'),
        ),
        migrations.AlterField(
            model_name='termreportsummary',
            name='total_points',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sum of grade_points across all subjects', max_digits=6),
        ),
        migrations.AlterField(
            model_name='termreportsummary',
            name='total_score',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sum of total_score across all subjects', max_digits=8),
        ),
        migrations.AlterUniqueTogether(
            name='subjectresult',
            unique_together={('student', 'classroom_subject', 'term', 'stage')},
        ),
        migrations.AlterUniqueTogether(
            name='termreportsummary',
            unique_together={('student', 'term', 'stage', 'class_group')},
        ),
    ]
