# Generated by Django 5.2.8 on 2026-04-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0005_alter_subjectresult_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectresult',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
