# Generated by Django 5.2.8 on 2026-01-31 16:37

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_studentsubjectenrollment'),
        ('grading', '0005_alter_targetgrade_student'),
        ('users', '0003_alter_studentprofile_admission_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gradescale',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='gradescale',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper(django.db.models.functions.text.Trim('grade')), models.F('school'), models.F('term'), models.F('class_room'), condition=models.Q(('is_active', True)), name='unique_active_grade_per_scope'),
        ),
        migrations.AddConstraint(
            model_name='gradescale',
            constraint=models.CheckConstraint(condition=models.Q(('min_score__lte', models.F('max_score'))), name='min_score_lte_max_score'),
        ),
        migrations.AddConstraint(
            model_name='gradescale',
            constraint=models.CheckConstraint(condition=models.Q(('min_score__gte', 0), ('max_score__lte', 100)), name='score_range_0_100'),
        ),
        migrations.AddConstraint(
            model_name='gradescale',
            constraint=models.CheckConstraint(condition=models.Q(('point__gte', 0), ('point__lte', 5)), name='point_between_0_and_5'),
        ),
    ]
