# Generated by Django 5.2.8 on 2025-12-07 12:09

import core.helper.models
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.CharField(default=core.helper.models.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the session e.g. 2024/2025', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Academic Session',
                'verbose_name_plural': 'Academic Sessions',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.CharField(default=core.helper.models.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='1st Term, 2nd Term, 3rd Term', max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('term_type', models.CharField(choices=[('HALF_TERM', 'Half Term'), ('END_OF_TERM', 'End of Term'), ('FULL_TERM', 'Full Term')], default='FULL_TERM', max_length=20)),
            ],
            options={
                'verbose_name': 'Academic Term',
                'verbose_name_plural': 'Academic Terms',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentPolicy',
            fields=[
                ('id', models.CharField(default=core.helper.models.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Default Policy', max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('ca_weight', models.PositiveIntegerField(default=40, help_text='Continuous Assessment weight (%)')),
                ('exam_weight', models.PositiveIntegerField(default=60, help_text='Examination weight (%)')),
            ],
            options={
                'verbose_name': 'Assessment Policy',
                'verbose_name_plural': 'Assessment Policies',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentRecord',
            fields=[
                ('id', models.CharField(default=core.helper.models.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('index', models.PositiveIntegerField(help_text='Test/Exam number e.g. 1 or 2')),
                ('score', models.FloatField(blank=True, null=True)),
                ('date_taken', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Assessment Record',
                'verbose_name_plural': 'Assessment Records',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentType',
            fields=[
                ('id', models.CharField(default=core.helper.models.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('CA', 'Continuous Assessment'), ('EXAM', 'Examination'), ('HALF_TERM', 'Half Term Exam'), ('PROJECT', 'Project'), ('ASSIGNMENT', 'Assignment')], default='CA', max_length=20)),
                ('count', models.PositiveIntegerField(default=1)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_score', models.PositiveIntegerField(default=100)),
                ('is_optional', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in reports')),
            ],
            options={
                'verbose_name': 'Assessment Type',
                'verbose_name_plural': 'Assessment Types',
                'ordering': ['policy', 'order', 'name'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.CharField(default=core.helper.models.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_class', models.CharField(choices=[('Nursery 1', 'Nursery 1'), ('Nursery 2', 'Nursery 2'), ('Prep', 'Preparatory'), ('Primary 1', 'Primary 1'), ('Primary 2', 'Primary 2'), ('Primary 3', 'Primary 3'), ('Primary 4', 'Primary 4'), ('Primary 5', 'Primary 5'), ('Primary 6', 'Primary 6'), ('JSS1', 'Junior Secondary 1'), ('JSS2', 'Junior Secondary 2'), ('JSS3', 'Junior Secondary 3'), ('SS1', 'Senior Secondary 1'), ('SS2', 'Senior Secondary 2'), ('SS3', 'Senior Secondary 3')], help_text='Parent academic class (JSS1, SS2 etc.)', max_length=20)),
                ('arm', models.CharField(help_text='Class arm e.g. A, B, C', max_length=10)),
            ],
            options={
                'ordering': ['academic_class', 'arm'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.CharField(default=core.helper.models.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_class', models.CharField(choices=[('Nursery 1', 'Nursery 1'), ('Nursery 2', 'Nursery 2'), ('Prep', 'Preparatory'), ('Primary 1', 'Primary 1'), ('Primary 2', 'Primary 2'), ('Primary 3', 'Primary 3'), ('Primary 4', 'Primary 4'), ('Primary 5', 'Primary 5'), ('Primary 6', 'Primary 6'), ('JSS1', 'Junior Secondary 1'), ('JSS2', 'Junior Secondary 2'), ('JSS3', 'Junior Secondary 3'), ('SS1', 'Senior Secondary 1'), ('SS2', 'Senior Secondary 2'), ('SS3', 'Senior Secondary 3')], max_length=50)),
                ('day_of_week', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=20)),
                ('room_number', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Class Schedule',
                'verbose_name_plural': 'Class Schedules',
                'db_table': 'class_schedules',
                'ordering': ['academic_class', 'day_of_week', 'time_slot__order'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.CharField(default=core.helper.models.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TeachingAssignment',
            fields=[
                ('id', models.CharField(default=core.helper.models.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Teaching Assignment',
                'verbose_name_plural': 'Teaching Assignments',
                'db_table': 'teaching_assignments',
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.CharField(default=core.helper.models.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_break', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Time Slot',
                'verbose_name_plural': 'Time Slots',
                'db_table': 'time_slots',
                'ordering': ['order', 'start_time'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.CharField(default=core.helper.models.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('academic_year', models.CharField(max_length=20)),
                ('term', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Timetable',
                'verbose_name_plural': 'Timetables',
                'db_table': 'timetables',
                'ordering': ['-start_date'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
