# Generated by Django 5.2.8 on 2026-04-04 08:17

import auto_prefetch
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='academicsession',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='users.school'),
        ),
        migrations.AddField(
            model_name='academicterm',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='users.school'),
        ),
        migrations.AddField(
            model_name='academicterm',
            name='session',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='academics.academicsession'),
        ),
        migrations.AddField(
            model_name='assessmentpolicy',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='users.school'),
        ),
        migrations.AddField(
            model_name='assessmentpolicy',
            name='term',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='academics.academicterm'),
        ),
        migrations.AddField(
            model_name='assessmentrecord',
            name='student',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_records', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='assessmenttype',
            name='policy',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_types', to='academics.assessmentpolicy'),
        ),
        migrations.AddField(
            model_name='assessmentrecord',
            name='assessment_type',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='academics.assessmenttype'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='form_teacher',
            field=auto_prefetch.ForeignKey(blank=True, help_text='Teacher assigned as the form teacher for this class', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_classes', to='users.teacherprofile'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='school',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='users.school'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_schedules', to='users.school'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='teacher',
            field=auto_prefetch.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentclassassignment',
            name='academic_session',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academicsession'),
        ),
        migrations.AddField(
            model_name='studentclassassignment',
            name='academic_term',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.academicterm'),
        ),
        migrations.AddField(
            model_name='studentclassassignment',
            name='classroom',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='academics.classroom'),
        ),
        migrations.AddField(
            model_name='studentclassassignment',
            name='student',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='studentsubjectenrollment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, help_text='Admin or staff who assigned this subject', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentsubjectenrollment',
            name='session',
            field=models.ForeignKey(help_text='Session in which this subject is assigned', on_delete=django.db.models.deletion.CASCADE, related_name='student_subject_enrollments', to='academics.academicsession'),
        ),
        migrations.AddField(
            model_name='studentsubjectenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_enrollments', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='studentsubjectenrollment',
            name='term',
            field=models.ForeignKey(help_text='Term in which this subject is assigned', on_delete=django.db.models.deletion.CASCADE, related_name='student_subject_enrollments', to='academics.academicterm'),
        ),
        migrations.AddField(
            model_name='subject',
            name='class_rooms',
            field=models.ManyToManyField(blank=True, help_text='Classrooms where this subject is taught. A subject may be assigned to multiple classrooms.', related_name='subjects', to='academics.classroom'),
        ),
        migrations.AddField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='users.school'),
        ),
        migrations.AddField(
            model_name='studentsubjectenrollment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='subject',
            field=auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='assessmentrecord',
            name='classroom_subject',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_records', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='classroom',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='academics.classroom'),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='subject',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='teacher',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='users.teacherprofile'),
        ),
        migrations.AddField(
            model_name='termperiod',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='users.school'),
        ),
        migrations.AddField(
            model_name='termperiod',
            name='term',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='academics.academicterm'),
        ),
        migrations.AddField(
            model_name='assessmentrecord',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.termperiod'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='users.school'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='time_slot',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='academics.timeslot'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='schedules',
            field=models.ManyToManyField(related_name='timetables', to='academics.classschedule'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='users.school'),
        ),
        migrations.AddConstraint(
            model_name='academicsession',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_session_per_school'),
        ),
        migrations.AlterUniqueTogether(
            name='academicterm',
            unique_together={('session', 'term_number')},
        ),
        migrations.AddConstraint(
            model_name='assessmentpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('school', 'term', 'is_active'), name='unique_active_policy_per_school_term'),
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('school', 'academic_class', 'arm')},
        ),
        migrations.AlterUniqueTogether(
            name='studentclassassignment',
            unique_together={('student', 'classroom', 'academic_session')},
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('school', 'code'), name='unique_active_subject_code_per_school'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('school', 'name'), name='unique_active_subject_name_per_school'),
        ),
        migrations.AlterUniqueTogether(
            name='studentsubjectenrollment',
            unique_together={('student', 'subject', 'session', 'term')},
        ),
        migrations.AlterUniqueTogether(
            name='teachingassignment',
            unique_together={('teacher', 'classroom', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='assessmentrecord',
            unique_together={('student', 'classroom_subject', 'assessment_type', 'index')},
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('school', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='classschedule',
            unique_together={('school', 'academic_class', 'day_of_week', 'time_slot')},
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('school', 'name', 'academic_year', 'term')},
        ),
    ]
