# Generated by Django 5.2.8 on 2026-03-05 14:57

import auto_prefetch
import core.helper.models
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('users', '0002_alter_school_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermPeriod',
            fields=[
                ('id', models.CharField(default=core.helper.models.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name of the period e.g Mid-Term Break', max_length=100)),
                ('period_type', models.CharField(choices=[('HALF_TERM', 'Half Term Break'), ('EXAM', 'Exam Period'), ('HOLIDAY', 'Holiday'), ('OTHER', 'Other')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'ordering': ['start_date'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='academicsession',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='academicsession',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Whether this session is currently active for the school', verbose_name='Active'),
        ),
        migrations.AddConstraint(
            model_name='academicsession',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_session_per_school'),
        ),
        migrations.AddField(
            model_name='termperiod',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='users.school'),
        ),
        migrations.AddField(
            model_name='termperiod',
            name='term',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='academics.academicterm'),
        ),
    ]
