# Generated by Django 5.2.8 on 2026-01-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='track',
            field=models.CharField(choices=[('SCIENCE', 'Science'), ('ARTS', 'Arts'), ('COMMERCIAL', 'Commercial')], default='SCIENCE', help_text='Academic track (Science, Arts, or Commercial)', max_length=20),
        ),
    ]
