# Generated by Django 5.2.8 on 2026-02-24 13:47

import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='form_teacher',
            field=auto_prefetch.ForeignKey(blank=True, help_text='Teacher assigned as the form teacher for this class', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_classes', to='users.teacherprofile'),
        ),
    ]
