# Generated by Django 5.2.8 on 2026-01-30 16:07

import auto_prefetch
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_classroom_track'),
        ('users', '0003_alter_studentprofile_admission_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'base_manager_name': 'prefetch_manager', 'ordering': ['name'], 'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='subject',
            name='credit_hour',
            field=models.PositiveSmallIntegerField(default=1, help_text='Academic weight of the subject. Used for GPA, CGPA, and weighted performance calculations.'),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_mandatory',
            field=models.BooleanField(default=False, help_text='Indicates whether this subject is mandatory for students in the assigned classrooms.'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='class_rooms',
            field=models.ManyToManyField(blank=True, help_text='Classrooms where this subject is taught. A subject may be assigned to multiple classrooms.', related_name='subjects', to='academics.classroom'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(help_text='Short unique subject code within the school (e.g., MTH101, ENG).', max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description providing additional details about the subject, such as scope, syllabus focus, or special notes.', null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates whether the subject is currently active. Inactive subjects are soft-deleted and hidden from normal listings.'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(help_text='Full name of the subject (e.g., Mathematics, English Language).', max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='school',
            field=auto_prefetch.ForeignKey(help_text='School that owns and manages this subject.', on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='users.school'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('school', 'code'), name='unique_active_subject_code_per_school'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('school', 'name'), name='unique_active_subject_name_per_school'),
        ),
    ]
