# Generated by Django 5.2.8 on 2026-04-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_assessmentrecord_remarks_assessmentrecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmenttype',
            name='period_type',
            field=models.CharField(blank=True, choices=[('HALF_TERM', 'Half Term Break'), ('EXAM', 'Exam Period'), ('HOLIDAY', 'Holiday'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
    ]
