# Generated by Django 5.2.8 on 2026-03-06 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_termperiod_alter_academicsession_unique_together_and_more'),
        ('users', '0002_alter_school_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='users.school'),
        ),
    ]
