# Generated by Django 5.2.8 on 2026-02-24 14:50

import auto_prefetch
import core.helper.models
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_classroom_form_teacher'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClassAssignment',
            fields=[
                ('id', models.CharField(default=core.helper.models.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_session', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academicsession')),
                ('academic_term', auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.academicterm')),
                ('classroom', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='academics.classroom')),
                ('student', auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='users.studentprofile')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
                'unique_together': {('student', 'classroom', 'academic_session')},
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
