# Generated by Django 5.2.8 on 2026-01-31 16:37

import core.helper.models
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_subject_options_alter_subject_unique_together_and_more'),
        ('users', '0003_alter_studentprofile_admission_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSubjectEnrollment',
            fields=[
                ('id', models.CharField(default=core.helper.models.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Admin or staff who assigned this subject', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(help_text='Session in which this subject is assigned', on_delete=django.db.models.deletion.CASCADE, related_name='student_subject_enrollments', to='academics.academicsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_enrollments', to='users.studentprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='academics.subject')),
                ('term', models.ForeignKey(help_text='Term in which this subject is assigned', on_delete=django.db.models.deletion.CASCADE, related_name='student_subject_enrollments', to='academics.academicterm')),
            ],
            options={
                'ordering': ['student', 'subject'],
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
                'unique_together': {('student', 'subject', 'session', 'term')},
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
