# Generated by Django 5.2.8 on 2026-04-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_assessmenttype_period_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='termperiod',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
