# Generated by Django 5.2.8 on 2026-04-20 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_termperiod_is_active'),
        ('users', '0005_alter_studentcontact_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicsession',
            name='school',
            field=models.ForeignKey(help_text='The school (tenant) this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='users.school'),
        ),
        migrations.AlterField(
            model_name='academicterm',
            name='school',
            field=models.ForeignKey(help_text='The school (tenant) this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='users.school'),
        ),
        migrations.AlterField(
            model_name='assessmentpolicy',
            name='school',
            field=models.ForeignKey(help_text='The school (tenant) this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='users.school'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(help_text='The school (tenant) this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='users.school'),
        ),
        migrations.AlterField(
            model_name='termperiod',
            name='school',
            field=models.ForeignKey(help_text='The school (tenant) this record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='users.school'),
        ),
    ]
